version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - JDBC_URL=jdbc:postgresql://postgres:5432/postgres  # the "postgres" hostname is equal to the "postgres" service name below.
      - JDBC_USERNAME=postgres
      - JDBC_PASSWORD=mysecretpassword
  postgres:
    image: "postgres:15.2"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
